import type { Metadata } from "next";
import "./globals.css";
import { Figtree } from "next/font/google";
import localFont from "next/font/local";
import Header from "@/app/_components/header/header";
import Footer from "@/app/_components/footer/footer";

const figtree = Figtree({
  display: "swap",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-figtree",
});

const yekan = localFont({
  src: [
    {
      path: "../../public/fonts/yekan/IRANYekanWebThin.woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "../../public/fonts/yekan/IRANYekanWebLight.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/fonts/yekan/IRANYekanWebRegular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/yekan/IRANYekanWebMedium.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/fonts/yekan/IRANYekanWebBold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/yekan/IRANYekanWebExtraBold.woff2",
      weight: "800",
      style: "normal",
    },
    {
      path: "../../public/fonts/yekan/IRANYekanWebExtraBlack.woff2",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-yekan",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" className={`dark ${figtree.variable} ${yekan.variable}`}>
      <body className="flex flex-col min-h-dvh dark:bg-base-100 dark:text-base-content">
        <Header />
        <main className="flex-1 container">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
